name: CI/CD Pipeline

on:
  push:
    paths:
      - 'Front End/index.html'
      - 'Front End/js/*.js'
      - 'Front End/css/*.css'
      - 'Front End/images/*.jpg'
      - 'Back End/lambda_function.py'
      - '.github/workflows/ci-cd.yml'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Run Cypress tests
        run: npm run cypress:run

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::713104041406:role/github_actions_user
          aws-region: us-east-1

      - name: Sync s3 bucket
        run: |
          aws s3 sync "Front End/" s3://crcsruthi --exclude "*" --include "index.html" --include "css/*.css" --include "js/*.js" --include "images/*.jpg" --delete

      - name: Zip Lambda function code
        run: |
          zip -r lambda_function.zip Back End/
      
      - name: Update Lambda function
        run: |
          aws lambda update-function-code --function-name crclambdasru --zip-file fileb://Back End/lambda_function.zip