name: Terraform

on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'
      - 'backend/**'
      - 'terraform/**'
jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.9.4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Initialize Terraform
      run: terraform init
      working-directory: ./terraform

    - name: Apply Terraform
      run: terraform apply -auto-approve -json | tee terraform_output.json
      working-directory: ./terraform

    - name: Extract bucket name
      id: extract_bucket_name
      run: |
        bucket_name=$(jq -r '.outputs.bucket_name.value' terraform/terraform_output.json)
        echo "bucket_name=$bucket_name" >> $GITHUB_ENV

    - name: Sync s3 bucket
      run: |
        aws s3 sync "frontend/" s3://$bucket_name --exclude "*" --include "index.html" --include "css/*.css" --include "js/*.js" --include "images/*.jpg" --delete
      env:
        bucket_name: ${{ env.bucket_name }}