name: Terraform

on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'
      - 'backend/**'
      - 'terraform/**'
jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.9.4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Initialize Terraform
      run: terraform init
      working-directory: ./terraform

    - name: Apply Terraform
      run: terraform apply -auto-approve -json | tee terraform_output.json
      working-directory: ./terraform
    
    - name: Parse Terraform output to retrieve Lambda function name
      id: lambda_function_name
      run: |
        lambda_name=$(jq -r '.values.root_module.outputs.lambda_name.value' terraform_output.json)
        echo "LAMBDA_NAME=$lambda_name" >> $GITHUB_ENV

    - name: Zip Lambda function code
      run: |
        cd backend
        zip -r ../lambda_function.zip .

    - name: Update Lambda function
      run: |
        aws lambda update-function-code --function-name ${{ env.LAMBDA_NAME }} --zip-file fileb://lambda_function.zip
    
