#This workflow runs only when changes are merged into the main branch. It handles updating AWS infrastructure.
name: Validate & Deploy

on:
  push:
    branches:
      - main
      - feature/*


jobs:
  deploy:
    runs-on: ubuntu-latest
    

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Sync s3 bucket
        run: |
          aws s3 sync "frontend/" s3://crcsruthi --exclude "*" --include "index.html" --include "css/*.css" --include "js/*.js" --include "images/*.jpg" --delete

      - name: Zip Lambda function code
        run: |
          cd backend
          zip -r ../lambda_function.zip .

      - name: Update Lambda function
        run: |
          aws lambda update-function-code --function-name crclsru --zip-file fileb://lambda_function.zip
      
      - name: Run Cypress tests
        run: npm run cypress:run